export const POST_GRADUATION_TYPES = {
  FOUR_YEAR_COLLEGE: '4 Year College',
  LESS_THAN_FOUR_YEAR_COLLEGE: 'Less 4 Year College',
  ADDITIONAL_HIGH_SCHOOL: 'Addl. High School',
  ARMED_FORCES: 'Armed Forces',
  EMPLOYED: 'Employed',
  UNEMPLOYED: 'Unemployed',
  UNKNOWN: 'Unknown'
} as const;

export const POST_GRADUATION_TYPE_ORDER = [
  POST_GRADUATION_TYPES.FOUR_YEAR_COLLEGE,
  POST_GRADUATION_TYPES.LESS_THAN_FOUR_YEAR_COLLEGE,
  POST_GRADUATION_TYPES.ADDITIONAL_HIGH_SCHOOL,
  POST_GRADUATION_TYPES.ARMED_FORCES,
  POST_GRADUATION_TYPES.EMPLOYED,
  POST_GRADUATION_TYPES.UNEMPLOYED,
  POST_GRADUATION_TYPES.UNKNOWN
] as const;

export const POST_GRADUATION_TYPES_WITH_TOOLTIP = [
  POST_GRADUATION_TYPES.ADDITIONAL_HIGH_SCHOOL
] as const;
